name: Deploy to GitHub Pages

on:
  pull_request:
    branches: [develop]
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: Build Visualization Docs
        working-directory: ./visualization-docs
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_DEPLOY }}
          publish_dir: ./visualization-docs/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com